add woo token metadata
aurora-is-near/bridge-assets pull request #122
Opened 2022-02-21 08:48 UTC by kevinwootrade

# Add WOO token metadata

ERC-20: https://etherscan.io/address/0x4691937a7508860f876c9c0a2a617e7d9e945d4b
NEP-141: https://explorer.mainnet.near.org/accounts/4691937a7508860f876c9c0a2a617e7d9e945d4b.factory.bridge.near
Aurora ERC-20: https://explorer.mainnet.aurora.dev/address/0x99ec8F13b2AFeF5eC49073B9D20df109D25F78c0

2022-02-21 18:05 UTC, sept-en requested changes
Thanks for the PR. Added a comment that needs to be addressed before merging.

2022-02-21 18:05 UTC, sept-en commented on tokens/woo.json
> +    "name": "WOO Network",
The token name should be the same as the ERC-20 token on Ethereum.

```suggestion
    "name": "Wootrade Network",
```

2022-02-21 18:05 UTC, sept-en approved these changes

2022-02-21 18:06 UTC, sept-en commented on tokens/woo.json
> +    "reference_hash": ""
```suggestion
    "ethereum_address": "0x4691937a7508860f876c9c0a2a617e7d9e945d4b",
    "near_address": "4691937a7508860f876c9c0a2a617e7d9e945d4b.factory.bridge.near",
    "aurora_address": "0x99ec8f13b2afef5ec49073b9d20df109d25f78c0",
    "name": "Wootrade Network",
    "symbol": "WOO",
    "decimals": 18,
    "icon": "",
    "reference": "",
    "reference_hash": ""
```

2022-02-21 18:07 UTC, merged

2022-02-23 03:07 UTC, kevinwootrade commented
Thanks for merging the PR, when will woo token show up on the rainbowbridge UI? thx