Add BSTN token metadata
aurora-is-near/bridge-assets pull request #129
Opened 2022-03-05 01:49 UTC by pysrbastion

# Add BSTN token metadata

ERC-20: https://etherscan.io/address/0x059a1f1dea1020297588c316ffc30a58a1a0d4a2
NEP-141: https://explorer.mainnet.near.org/accounts/059a1f1dea1020297588c316ffc30a58a1a0d4a2.factory.bridge.near
Aurora ERC-20: https://explorer.mainnet.aurora.dev/address/0x9f1F933C660a1DC856F0E0Fe058435879c5CCEf0

2022-03-05 21:14 UTC, sept-en requested changes

2022-03-05 21:14 UTC, sept-en commented on tokens/bstn.json
> +  "icon": "data:image/svg+xml,%3csvg width='50' height='50' viewBox='0 0 50 50' fill='none' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3e %3crect width='50' height=
Please, make sure it contains 4 spaces

2022-03-05 21:14 UTC, sept-en commented on tokens/bstn.svg
> +<svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
The icon is too big. Please reduce it to 5-7 kB at max.

2022-03-06 02:52 UTC, pysrbastion commented
@sept-en fixed

2022-03-06 21:10 UTC, merged

2022-03-06 21:10 UTC, sept-en reviewed
Approved.