Add rMC token metadata
aurora-is-near/bridge-assets pull request #137
Opened 2022-03-19 06:16 UTC by jirosaito

ERC-20: https://etherscan.io/address/0x39A15a0695c77cbe5fd4F06AB0cCB7bAd62F696F
NEP-141: https://explorer.mainnet.near.org/accounts/39a15a0695c77cbe5fd4f06ab0ccb7bad62f696f.factory.bridge.near
Aurora ERC-20: https://explorer.mainnet.aurora.dev/address/0xd9a4C034e69e5162AC02BEc627475470a53C9a14

2022-03-19 06:17 UTC, jirosaito commented
cc @sept-en

2022-03-20 22:25 UTC, sept-en requested changes

2022-03-20 22:25 UTC, sept-en commented on tokens/rmc.json
> +    "near_address": "39a15a0695c77cbe5fd4f06ab0ccb7bad62f696f.factory.bridge.near",
```suggestion
    "ethereum_address": "0x39a15a0695c77cbe5fd4f06ab0ccb7bad62f696f",
    "near_address": "39a15a0695c77cbe5fd4f06ab0ccb7bad62f696f.factory.bridge.near",
    "aurora_address": "0xd9a4c034e69e5162ac02bec627475470a53c9a14",
    "name": "rMutantCoin",
    "symbol": "rMC",
    "decimals": 18,
```

2022-03-20 22:27 UTC, sept-en approved these changes

2022-03-20 22:28 UTC, merged

2022-03-20 23:50 UTC, jirosaito commented
<img width="656" alt="Screen Shot 2022-03-20 at 4 48 14 PM" src="https://user-images.githubusercontent.com/82254787/159191301-ae70e3af-57ee-4b7e-bfd3-8e4dc489a805.png">

Thanks for merging @sept-en. The token metadata has been updated on NEP but not on Aurora (screenshot). Could you please check to update the metadata on Aurora? Thank you