Add Tusd Token metadata
aurora-is-near/bridge-assets pull request #141
Opened 2022-03-23 08:32 UTC by leon8866

ERC-20: https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376
NEP-141: https://explorer.mainnet.near.org/accounts/0000000000085d4780b73119b644ae5ecd22b376.factory.bridge.near
Aurora ERC-20: https://explorer.mainnet.aurora.dev/address/0x5454bA0a9E3552f7828616D80a9D2D869726e6F5

AuroraScan: https://aurorascan.dev/address/0x5454bA0a9E3552f7828616D80a9D2D869726e6F5

2022-03-23 21:59 UTC, sept-en requested changes

2022-03-23 21:59 UTC, sept-en commented on tokens/tusd.json
> +    "near_address": "0000000000085d4780b73119b644ae5ecd22b376.factory.bridge.near",
```suggestion
    "near_address": "0000000000085d4780b73119b644ae5ecd22b376.factory.bridge.near",
    "aurora_address": "0x5454ba0a9e3552f7828616d80a9d2d869726e6f5",
```

2022-03-23 22:03 UTC, sept-en approved these changes
Thanks for your PR. LGTM!

2022-03-23 22:03 UTC, merged

2022-03-24 05:58 UTC, leon8866 commented
Hello, have we successfully deployed the tusd contract on Aurora? I can't see the metadata change yet