Add PRESENCE token metadata
aurora-is-near/bridge-assets pull request #223
Opened 2022-09-03 13:08 UTC by bridgitbrowser

ERC-20: https://etherscan.io/address/0xC6903B623f1548f533Eb367f6f1B7d717b9351c2
NEP-141: https://explorer.mainnet.near.org/accounts/c6903b623f1548f533eb367f6f1b7d717b9351c2.factory.bridge.near
Aurora ERC-20 (BlockScout): https://explorer.mainnet.aurora.dev/address/0xf6db8e249099b909a764e46a9cc0c9309dcfd0ce
Aurora ERC-20 (Aurorascan): https://aurorascan.dev/address/0xf6db8e249099b909a764e46a9cc0c9309dcfd0ce

2022-09-03 13:09 UTC, bridgitbrowser commented
I just added the Aurora token

2022-09-03 15:06 UTC, bridgitbrowser commented
Hi there, it put these two tokens together in the same pull request. I hope that's ok.

2022-09-03 18:27 UTC, sept-en commented
@bridgitbrowser please split two tokens into separate PRs. This is needed for sanity.

2022-09-10 18:39 UTC, bridgitbrowser commented
Ok, I removed the BRGT so the pull request is just the PRESENCE token

2022-09-10 18:40 UTC, bridgitbrowser commented
I this ok? the pull request is just PRESENCE now

2022-09-14 22:55 UTC, sept-en requested changes

2022-09-14 22:55 UTC, sept-en commented on tokens/presence.json
> +    "name": "Pressence DAO",
```suggestion
    "name": "Presence DAO",
```

2022-09-14 22:55 UTC, sept-en approved these changes

2022-09-14 22:56 UTC, merged