Add mock tokens metadata: mock wNEAR, USDT, USDC, CORN, LINEAR
aurora-is-near/bridge-assets pull request #242
Opened 2022-11-10 05:58 UTC by think-in-universe

# Add Mock wNEAR, USDT, USDC, CORN, LINEAR token metadata

We propose to add the mock tokens for testing purpose of Cornerstone project. We understand there might be concerns of adding mock tokens, so please review whether it's feasible to do that. 

## Mock wNEAR

NEP-141: https://explorer.mainnet.near.org/accounts/wnear.mocks.near
Aurora ERC-20: https://aurorascan.dev/address/0x94b8bffc250c5aa3e13e8d864dd5fdedab54cb29

## Mock USDT

NEP-141: https://explorer.mainnet.near.org/accounts/usdt.mocks.near
Aurora ERC-20: https://aurorascan.dev/address/0x8f49abd8af60ca1b27ae796c1015fe696c316f74

## Mock USDC

NEP-141: https://explorer.mainnet.near.org/accounts/usdc.mocks.near
Aurora ERC-20: https://aurorascan.dev/address/0x8910fbcf56fd981b485648869b9ccee7305aa08d

## Mock LINEAR

NEP-141: https://explorer.mainnet.near.org/accounts/linear.mocks.near
Aurora ERC-20: https://aurorascan.dev/address/0x45de93fdfb16508823da91819ee891eb78fe028a

## Mock CORN

NEP-141: https://explorer.mainnet.near.org/accounts/corn.v1.corn-staging.near
Aurora ERC-20: https://aurorascan.dev/address/0x096f9fdda1e6f59ad2a8216bbd64daa9140222cc

2022-11-18 01:54 UTC, sept-en requested changes
Hi @think-in-universe, thanks for your PR.
There's no issue with adding mocked tokens. However, what I can see in PR - you have different metadata for NEP-141 token and the one in the PR. Unfortunately, we have a requirement that metadata on all networks should match. Moreover, the name of the file should be its symbol. For example, if we have NEP-141 with metadata "wNEAR", but we set "MOCK-wNEAR" for the corresponding token on Aurora - that would create a lot of mess.

I'm happy to accept the PR with the mock tokens in case these tokens have that metadata in NEP-141 token. I'd also recommend changing icons, so it's clear that it's not the original token by name, symbol, and icon.

2022-11-18 01:54 UTC, sept-en commented on tokens/mock_linear.json
> +    "symbol": "MOCK-LINEAR",
```suggestion
    "name": "LiNEAR",
    "symbol": "LINEAR",
```

2022-11-18 01:54 UTC, sept-en commented on tokens/mock_usdc.json
> +    "symbol": "MOCK-USDC",
```suggestion
    "name": "USD Coin",
    "symbol": "USDC",
```

2022-11-18 01:54 UTC, sept-en commented on tokens/mock_usdt.json
> +    "symbol": "MOCK-USDT",
```suggestion
    "name": "Tether USD",
    "symbol": "USDT.e",
```

2022-11-18 01:54 UTC, sept-en commented on tokens/mock_wnear.json
> +    "symbol": "MOCK-wNEAR",
```suggestion
    "name": "Wrapped NEAR fungible token",
    "symbol": "wNEAR",
```

2022-11-18 06:39 UTC, think-in-universe commented
@sept-en thanks for the suggestions, Kirill. 

We have updated the FT metadata of the mocked tokens are NEAR, and now they should match with the metadata in the JSON files in the PR. Could you please check? I also updated the filename of `mock_usdt` to `mock_usdt.e`.

For the icons, yeah, I agree ideally the icons should be different, but it would take some time for us to design a suite of mock icons, so I suggest we don't change the icons this time. 

Please let me know in case there're other questions or concerns.

2022-11-19 23:59 UTC, sept-en requested changes

2022-11-19 23:59 UTC, sept-en commented on tokens/mock_corn.json
> +    "near_address":"corn.v1.corn-staging.near",
```suggestion
    "near_address": "corn.v1.corn-staging.near",
    "aurora_address": "0x096f9fdda1e6f59ad2a8216bbd64daa9140222cc",
```

2022-11-19 23:59 UTC, sept-en commented on tokens/mock_linear.json
> +    "near_address":"linear.mocks.near",
```suggestion
    "near_address": "linear.mocks.near",
    "aurora_address": "0x45de93fdfb16508823da91819ee891eb78fe028a",
```

2022-11-19 23:59 UTC, sept-en commented on tokens/mock_usdc.json
> +    "near_address":"usdc.mocks.near",
```suggestion
    "near_address": "usdc.mocks.near",
    "aurora_address": "0x8910fbcf56fd981b485648869b9ccee7305aa08d",
```

2022-11-19 23:59 UTC, sept-en approved these changes

2022-11-19 23:59 UTC, merged

2022-11-21 04:01 UTC, think-in-universe commented
@sept-en Hey Kirill, thanks for merging the PR 😄 

It seems the metadatas are not updated yet. Do you know when the metadata will be updated?