Add EURe token metadata
aurora-is-near/bridge-assets pull request #253
Opened 2023-03-20 11:00 UTC by PierreLeGuen

ERC-20: https://etherscan.io/address/0x3231cb76718cdef2155fc47b5286d82e6eda273f 
NEP-141: https://nearblocks.io/address/3231cb76718cdef2155fc47b5286d82e6eda273f.factory.bridge.near 
Aurora ERC-20: https://explorer.aurora.dev/address/0xbF7d2104C990D1e91F3e1Dc7E1418ae9AF2c8D8A

2023-03-20 23:10 UTC, sept-en requested changes
Thanks for your PR. I added a NEP-141 address too, which is needed for consistency.

2023-03-20 23:10 UTC, sept-en commented on tokens/EURe.json
> +    "aurora_address": "0xbf7d2104c990d1e91f3e1dc7e1418ae9af2c8d8a",
```suggestion
    "ethereum_address": "0x3231cb76718cdef2155fc47b5286d82e6eda273f",
    "near_address": "3231cb76718cdef2155fc47b5286d82e6eda273f.factory.bridge.near",
    "aurora_address": "0xbf7d2104c990d1e91f3e1dc7e1418ae9af2c8d8a",
```

2023-03-20 23:12 UTC, sept-en approved these changes
The token metadata will be updated within the week.

2023-03-20 23:12 UTC, merged

2023-03-21 09:08 UTC, PierreLeGuen commented
@sept-en would be good to add the NEP-141 (`near_address`) field in the `EXAMPLE_token.json`.