Add XPOLAR token
aurora-is-near/bridge-assets pull request #313
Opened 2024-10-28 13:25 UTC by Karkunow

Token request from Polaris team

2024-10-28 13:52 UTC, alexandermendes approved these changes

2024-10-28 16:39 UTC, karim-en requested changes

2024-10-28 16:39 UTC, karim-en commented on tokens/xpolar.json
> +    "icon": "data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20id%3D%22Layer_1%22%20data-name%3D%22Layer%201%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%
```suggestion
    "icon": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1ODQuODUgNTY3LjEyIj4KICA8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLmNscy0xIHsKICAgICAgICBmaWxsOiAjZmNmY2ZkOwogICAgICB9CgogICAgICAuY2xzLTIgewogICAgICAgIGZpbGw6ICM3ZTAyZjU7CiAgICAgIH0KCiAgICAgIC5jbHMtMyB7CiAgICAgICAgZmlsbDogI2ZmZjsKICAgICAgfQoKICAgICAgLmNscy00IHsKICAgICAgICBmaWxsOiAjN2QwMmYyOwogICAgICB9CgogICAgICAuY2xzLTUgewogICAgICAgIGZpbGw6ICM3ZDAyZjM7CiAgICAgIH0KCiAgICAgIC5jbHMtNiB7CiAgICAgICAgZmlsbDogIzdkMDJmNDsKICAgICAgfQoKICAgICAgLmNscy03IHsKICAgICAgICBmaWxsOiAjZmRmZGZlOwogICAgICB9CgogICAgICAuY2xzLTggewogICAgICAgIGZpbGw6ICMxMzA3MTk7CiAgICAgIH0KCiAgICAgIC5jbHMtOSB7CiAgICAgICAgZmlsbDogIzdjMDJmMDsKICAgICAgfQoKICAgICAgLmNscy0xMCB7CiAgICAgICAgZmlsbDogI2ZlZmVmZTsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2RlZnM+CiAgPGVsbGlwc2UgY2xhc3M9ImNscy04IiBjeD0iMjkyLjQyIiBjeT0iMjgzLjU2IiByeD0iMjkyLjQyIiByeT0iMjgzLjU2Ii8+CiAgPHBhdGggY2xhc3M9ImNscy0xMCIgZD0iTTQ2Ni44OSwyNDguMTNjMy4yMSwxNS4zMSw0LjI2LDMwLjUyLDMuMzUsNDUuODctMS4xNiwxOS43OC01LjQsMzguODYtMTIuOTMsNTcuMTgtNy4zOCwxNy45OC0xNy4yOSwzNC40Mi0zMC4yNSw0OC45Ni0zLjk3LDQuNDYtOC4xNCw4Ljc1LTEyLjQ4LDEzLjQtMTkuMjMtMzcuOTctMzguMjEtNzUuNDQtNTcuMjctMTEzLjA2LDkuNDItNi4yMywxNy4wMi0xMy45MiwyMi42Mi0yNC43Mi0xMC41NSwzLjI1LTIwLjI3LDYuMjUtMzAsOS4yNS0xLjkxLTEuNzItMi4wMi0zLjMyLS44Ni01LjQ5LDQuOC04LjkxLDkuMzUtMTcuOTUsMTQuMjEtMjYuODMsLjc5LTEuNDQsMi40Ni0yLjcyLDQuMDItMy4zNywxNS41Ni02LjQ2LDMwLjY5LTEzLjcxLDQ0LjE2LTI0LDEzLjItMTAuMDgsMjMuMTktMjIuNzYsMzAuNTItMzguMjUsMTIuMjMsMTguOTQsMjAuNSwzOS4wNywyNC45MSw2MS4wOFoiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTYiIGQ9Ik0yMTMuMTUsMjE5LjNjMy41OSw2Ljk4LDcuMDYsMTMuNzYsMTAuODQsMjEuMTMtNTQuMTgsMTAuODYtODcuOTMsNDIuOC0xMDEuMzIsOTYuMzMtNi44NS0xOS41Ni05LjI1LTM5LjctOC4yOC02MC4yLDIuNDMtNTEuNDUsMjMuMzYtOTQuMDUsNjIuMTMtMTI4LjU5LDEyLjM2LDI0LjA4LDI0LjQ0LDQ3LjYxLDM2LjYzLDcxLjM0WiIvPgogIDxwYXRoIGNsYXNzPSJjbHMtMTAiIGQ9Ik0zMzMuOTcsNDEzLjQ4YzUuOCwxMi42OSwxMS41MiwyNS4xNiwxNy40NywzOC4xNC0zLjkzLDEuMjEtNy43LDIuNDUtMTEuNTIsMy41Mi0xNS4zMSw0LjI5LTMwLjk2LDYuMzUtNDYuODIsNi4zNy0xMy4yMywuMDItMjYuNDktMS4wMS0zOS4yNC00LjY2LTMuODEtMS4wOS02Ljg4LTQuODktMTAuMTItNy42Ni0uMzgtLjMyLC4yMS0yLjA3LC42NC0zLjAxLDE0LjgzLTMyLjE0LDI5LjctNjQuMjYsNDQuNTYtOTYuMzgsMS45MS00LjEyLDMuNzgtOC4yNiw1Ljc4LTEyLjMzLC40NC0uODksMS4zNy0xLjUzLDIuMDctMi4yOSwuNzksLjgsMS44OCwxLjQ1LDIuMzIsMi40MSwxMS42MywyNS4yLDIzLjE4LDUwLjQ0LDM0LjgzLDc1Ljg5WiIvPgogIDxwYXRoIGNsYXNzPSJjbHMtNiIgZD0iTTI2MS42OCwxMDcuOTdjMTEuNjctLjkxLDIzLjA3LTIuMzcsMzQuNDgtMi40MiwxMi45OC0uMDYsMjYuMDMsLjk0LDM4LjQyLDUuMzIsNC40MSwxLjU2LDguNDMsNC4yNywxMi41MSw2LjY2LDEuNjcsLjk4LDIuMzYsMi4zNiwxLjM0LDQuNjUtNy44MiwxNy41Ni0xNS40MSwzNS4yMS0yMy4yMiw1Mi43Ny0uNjIsMS40LTIuMTksMi44Ni0zLjYzLDMuMzUtMTQuMzgsNC44MS0yOC44Miw5LjQ1LTQzLjI4LDE0LjAxLS43NiwuMjQtMi40Ny0uNDItMi43Ny0xLjA5LTExLjUzLTI1Ljg2LTIyLjk0LTUxLjc3LTM0LjM3LTc3LjY3LS4wNC0uMDgsLjAyLS4yLC4xMS0uOTgsNi41Ny0xLjQ3LDEzLjM2LTMsMjAuNDEtNC41OVoiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xNjguMDksNDAxLjEzYy02LjUzLTkuNzktMTEuODQtMTkuOTQtMTMuOTgtMzEuMzctMy43NS0yMC4wNywuNzItMzguNTIsMTEuNzYtNTUuNTEsNy41Mi0xMS41NywxOC4zLTE5LjQsMzAuMTYtMjUuOSwxMi45Mi03LjA4LDI2LjU1LTEyLjQsNDAuODctMTUuOTksMi41My0uNjMsMy4zOSwuMjEsNC44MSwyLjIsMy41Nyw1LjAyLDMuMjYsOS40MSwuMDksMTQuNTctMy42LDUuODctNi40NCwxMi4yMy05LjM5LDE4LjQ3LTEuMDIsMi4xNi0yLjQ2LDMuMzMtNC42MSw0LjE0LTEzLjAyLDQuODgtMjQuMjYsMTIuNC0zMi44OSwyMy4zNy05LjIsMTEuNjktMTMuNywyNS4yNS0xNC44Nyw0MC4wMS0uNjksOC42MywwLDE3LjE2LDEuODYsMjUuNTQsLjc4LDMuNSwuNyw2LjM5LTEuMjMsOS4zNS0uOTksMS41My0xLjY4LDMuMjUtMi44MSw1LjQ3LTMuNDItNS4wNS02LjUyLTkuNjItOS43Ni0xNC4zN1oiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0zMzIsMzg2Ljg3Yy0xMC41OS0yMi44NC0yMS4wNS00NS40OS0zMS43LTY4LjU4LDEzLjgxLTMuODQsMjcuMzctNy42MSw0MS4wNy0xMS40Miw1LjY5LDExLjQsMTEuMzgsMjIuODgsMTcuMTQsMzQuMzMsNywxMy45LDE0LjA4LDI3Ljc1LDIxLjEsNDEuNjQsMi42NCw1LjIzLC43OCw4LjIyLTUuMDcsOC4yMi0xMS43OSwwLTIzLjU5LDAtMzUuMzgsMC0zLjExLDAtNS41My0xLjE5LTcuMTYtNC4xOVoiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTciIGQ9Ik0yNzMuOTYsMjA0LjA2YzIuOTksNS44NSw1Ljc0LDExLjY3LDguNDMsMTcuNTEsMS4xNSwyLjUxLDIuMiw1LjA2LDMuNDYsNy45Ni0zLjgxLC40Ny03LjM5LC44MS0xMC45NCwxLjM2LTkuNTksMS40OS0xOS4xNywzLjAyLTI4LjczLDQuNjYtMS44LC4zMS0yLjY3LDAtMy41NC0xLjcyLTguODEtMTcuMzMtMTcuNzUtMzQuNi0yNi42Mi01MS45LTIuNzYtNS4zOS0uNjEtOC44Niw1LjQ3LTguODgsMTAuMTUtLjAzLDIwLjMsLjAxLDMwLjQ1LS4wMSw2LjA3LS4wMSwxMC40NiwyLjI1LDEyLjY4LDguMzEsMS42Miw0LjQxLDMuNzcsOC42MSw1LjgxLDEzLjItMTIuOCwzLjUyLTI1LjMxLDYuOTYtMzcuODMsMTAuNHYuNTljMTMuNy0uNSwyNy40LTEsNDEuMzYtMS40OFoiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik0yMjcuOCwzNjMuMDdjMTEuNy0xOC4zOCwyOC4wOC0zMC4zMSw0OC4zNi0zNy4xMiw0Ljg2LTEuNjMsOS43NC0zLjIsMTUuMzktNS4wNS0uNjEsMS42Mi0uODksMi41My0xLjI4LDMuMzgtOS4wMywxOS41Ni0xOC4xNSwzOS4wOC0yNy4wOSw1OC42OC0yLjU2LDUuNjEtNi4yOCw4LjQyLTEyLjcyLDguMi0xMC4zMS0uMzUtMjAuNjUtLjA5LTMxLjM4LS4wOSwuMjItMTAuMjcsMy44NS0xOS4yMSw4LjcyLTI3Ljk5WiIvPgogIDxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTI1NC44NCwzMDUuMTdjLS4yOC0uNjktLjYyLTEuNTYtLjM0LTIuMTEsMy40Ni03LjAzLDYuOTYtMTQuMDQsMTAuNTctMjEsLjktMS43MywuOTctMy4xNCwwLTQuODUtMS41My0yLjY2LTIuODQtNS40Ni00LjQ4LTguNjQsMjYuMzUtMS4zMyw1Mi4xMi00LjA4LDc3Ljk1LTEwLjc0LTMuNjEsNi45NS02LjgyLDEzLjI5LTEwLjIxLDE5LjU0LS44OSwxLjY0LTEuMDEsMi44OS0uMDUsNC41MiwxLjQsMi4zOSwyLjUzLDQuOTUsMy45NSw3LjgxLTI1Ljg4LDUuMTgtNTEuNTEsMTAuMzEtNzcuMzcsMTUuNDZaIi8+CiAgPHBhdGggY2xhc3M9ImNscy0zIiBkPSJNMzcxLjExLDE4Ni40N2MyLjE1LTEuMDYsNC4wOS0yLDYuNjktMy4yNC00LjgzLDkuMjctOS4zNiwxNy45Ny0xMy45MSwyNi42Ny0uMzcsLjcxLTEuMDUsMS4zMy0xLjIxLDIuMDctMS4zLDUuOTctNi4wMSw3LjMyLTExLjAzLDguMTktMTAuOSwxLjg5LTIxLjgsMy43OC0zMi43MSw1LjU3LTMuMjcsLjU0LTYuNiwuNzQtMTAuMjUsMS4xNCwxLjg1LTQuMzcsMy42My04LjcsNS41LTEyLjk5LDIuMDMtNC42Nyw0LTkuMzcsNi4yOS0xMy45LC41My0xLjA1LDIuMjMtMS45MiwzLjUtMi4xMSwxNS41OS0yLjI5LDMwLjkyLTUuNjUsNDUuODMtMTAuNzcsLjM3LS4xMywuNzItLjMzLDEuMjktLjYzWiIvPgogIDxwYXRoIGNsYXNzPSJjbHMtOSIgZD0iTTM5OC4wMiwxODUuOTRjNS41NS0xMC42MywxMS4wMS0yMS4wNSwxNi41Ny0zMS42OCwyLjY1LDEuOCw0Ljc5LDMuNTQsNS4xMiw2Ljk1LDEuMzUsMTQuMjMtMy4yOCwyNi4wNS0xNC41NywzNC44MS01LjI4LDQuMS0xMS4yNyw3LjI3LTE2Ljk0LDEwLjg2LS4yMi0uMjctLjQ1LS41My0uNjctLjgsMy40Ny02LjY0LDYuOTMtMTMuMjgsMTAuNS0yMC4xM1oiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik0yOTcuNTIsMjAxLjYxYzUuNjctLjcxLDExLjA3LTEuMzYsMTYuOTUtMi4wNy0xLjA2LDIuNS0xLjkzLDQuNTctMi44Miw2LjYyLTIuNzcsNi4zNS01LjYzLDEyLjY2LTguMjcsMTkuMDYtLjgzLDIuMDMtMi4wNSwyLjk0LTQuMTIsMy0uNzIsLjAyLTEuNDQsLjEtMi4xNiwuMTRxLTUuMTIsLjMxLTcuMjktNC42Yy0yLjkyLTYuNjEtNS44NS0xMy4yMS05LjAxLTIwLjM1LDUuNzMtLjYxLDExLjA5LTEuMTgsMTYuNzItMS44WiIvPgo8L3N2Zz4=", 
```

2024-10-28 16:39 UTC, karim-en commented on tokens/xpolar.json
> +    "icon": "data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Csvg%20id%3D%22Layer_1%22%20data-name%3D%22Layer%201%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%
Please convert it to base64
https://codebeautify.org/svg-to-base64-converter

2024-10-29 13:49 UTC, Karkunow commented
@karim-en done

2024-10-29 14:02 UTC, karim-en approved these changes

2024-10-29 14:02 UTC, merged