Add xTRI metadata
aurora-is-near/bridge-assets pull request #57
Opened 2021-12-19 09:54 UTC by 0xdon

# Add xTRI metadata

ERC-20: https://explorer.mainnet.aurora.dev/address/0x802119e4e253D5C19aA06A5d567C5a41596D6803/transactions

2021-12-23 20:00 UTC, sept-en requested changes
Thanks for your PR! Your icon is too big, please adjust it to have a size of 5-7 KBs.

2022-02-25 12:02 UTC, 0xdon commented
> Thanks for your PR! Your icon is too big, please adjust it to have a size of 5-7 KBs.

Changed the icon size to be lower than 5 KBs

2022-02-25 23:43 UTC, sept-en requested changes

2022-02-25 23:43 UTC, sept-en commented on tokens/xtri.json
> +    "icon": "",
```suggestion
    "icon": "data:image/svg+xml,%3C%3Fxml version='1.0' encoding='UTF-8'%3F%3E%3Csvg width='494px' height='496px' viewBox='0 0 494 496' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3Ctitle%3ExTRI Logo 2%3C/title%3E%3Cdefs%3E%3ClinearGradient x1='26.6668214%25' y1='11.473941%25' x2='133.4948%25' y2='143.731618%25' id='linearGradient-memk6wle0w-1'%3E%3Cstop stop-color='%2300FFB1' offset='0%25'%3E%3C/stop%3E%3Cstop stop-color='%237FB2FF' offset='29.8295635%25'%3E%3C/stop%3E%3Cstop stop-color='%23FFFFFF' stop-opacity='0' offset='100%25'%3E%3C/stop%3E%3C/linearGradient%3E%3CradialGradient cx='20.8875394%25' cy='94.9008553%25' fx='20.8875394%25' fy='94.9008553%25' r='39.6153719%25' gradientTransform='translate(0.208875,0.949009),scale(1.000000,0.995968),rotate(-52.001683),scale(1.000000,1.250805),translate(-0.208875,-0.949009)' id='radialGradient-memk6wle0w-2'%3E%3Cstop stop-color='%23C5CB16' offset='0%25'%3E%3C/stop%3E%3Cstop stop-color='%23D5F600' offset='54.2937853%25'%3E%3C/stop%3E%3Cstop stop-color='%23FFFFFF' stop-opacity='0' offset='100%25'%3E%3C/stop%3E%3C/radialGradient%3E%3CradialGradient cx='17.318119%25' cy='94.5193204%25' fx='17.318119%25' fy='94.5193204%25' r='319.665001%25' gradientTransform='translate(0.173181,0.945193),scale(1.000000,0.995968),rotate(-69.654557),scale(1.000000,1.250805),translate(-0.173181,-0.945193)' id='radialGradient-memk6wle0w-3'%3E%3Cstop stop-color='%23FFFFFF' stop-opacity='0' offset='0%25'%3E%3C/stop%3E%3Cstop stop-color='%23E7FFE7' stop-opacity='0.095354916' offset='6.92166%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FF00' offset='11.1224305%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FFD1' offset='13.2565104%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FFD1' stop-opacity='0' offset='18.5822316%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FFD1' stop-opacity='0' offset='100%25'%3E%3C/stop%3E%3C/radialGradient%3E%3CradialGradient cx='102.881663%25' cy='81.4227078%25' fx='102.881663%25' fy='81.4227078%25' r='298.019869%25' gradientTransform='translate(1.028817,0.814227),scale(1.000000,0.995968),rotate(-135.027163),scale(1.000000,1.122109),translate(-1.028817,-0.814227)' id='radialGradient-memk6wle0w-4'%3E%3Cstop stop-color='%23FFFFFF' stop-opacity='0' offset='0%25'%3E%3C/stop%3E%3Cstop stop-color='%23E7FFE7' stop-opacity='0.095354916' offset='6.92166%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FF00' offset='11.1224305%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FFD1' offset='13.2565104%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FFD1' stop-opacity='0' offset='25.171244%25'%3E%3C/stop%3E%3Cstop stop-color='%2300FFD1' stop-opacity='0' offset='100%25'%3E%3C/stop%3E%3C/radialGradient%3E%3CradialGradient cx='103.780817%25' cy='73.2654346%25' fx='103.780817%25' fy='73.2654346%25' r='39.5772682%25' gradientTransform='translate(1.037808,0.732654),scale(1.000000,0.995968),rotate(-141.776847),scale(1.000000,1.250805),translate(-1.037808,-0.732654)' id='radialGradient-memk6wle0w-5'%3E%3Cstop stop-color='%23C5CB16' offset='0%25'%3E%3C/stop%3E%3Cstop stop-color='%23D5F600' offset='54.2937853%25'%3E%3C/stop%3E%3Cstop stop-color='%23FFFFFF' stop-opacity='0' offset='100%25'%3E%3C/stop%3E%3C/radialGradient%3E%3C/defs%3E%3Cg id='Page-1' stroke='none' stroke-width='1' fill='none' fill-rule='evenodd'%3E%3Cg id='svg'%3E%3Cg id='Gradients'%3E%3Cellipse id='Gradient-Linear-BG' fill='url(%23linearGradient-memk6wle0w-1)' cx='247' cy='248' rx='247' ry='248'%3E%3C/ellipse%3E%3Cellipse id='Gradient-Radial-Yellow-1' fill='url(%23radialGradient-memk6wle0w-2)' cx='247' cy='248' rx='247' ry='248'%3E%3C/ellipse%3E%3Cellipse id='Gradient-Radial-Rings-1' fill='url(%23radialGradient-memk6wle0w-3)' cx='247' cy='248' rx='247' ry='248'%3E%3C/ellipse%3E%3Cellipse id='Gradient-Radial-Rings-2' fill='url(%23radialGradient-memk6wle0w-4)' cx='247' cy='248' rx='247' ry='248'%3E%3C/ellipse%3E%3Cellipse id='Gradient-Radial-Yellow-2' fill='url(%23radialGradient-memk6wle0w-5)' cx='247' cy='248' rx='247' ry='248'%3E%3C/ellipse%3E%3C/g%3E%3Cg id='T' transform='translate(104.000000, 87.000000)' fill='%23000000'%3E%3Crect id='Rectangle' x='0' y='0' width='285' height='56' rx='28'%3E%3C/rect%3E%3Crect id='Rectangle' x='109' y='16' width='68' height='327' rx='34'%3E%3C/rect%3E%3C/g%3E%3Cellipse id='Border' stroke='%23000000' stroke-width='15' cx='247' cy='248' rx='239.5' ry='240.5'%3E%3C/ellipse%3E%3C/g%3E%3C/g%3E%3C/svg%3E",
```

2022-02-25 23:44 UTC, sept-en approved these changes

2022-02-25 23:44 UTC, merged