Add PICKLE token metadata
aurora-is-near/bridge-assets pull request #62
Opened 2021-12-23 00:22 UTC by larrythecucumber321

# Add PICKLE token metadata

ERC-20: https://etherscan.io/address/0x429881672B9AE42b8EbA0E26cD9C73711b891Ca5
NEP-141: https://explorer.near.org/accounts/429881672b9ae42b8eba0e26cd9c73711b891ca5.factory.bridge.near

2021-12-23 09:22 UTC, sept-en requested changes
Thanks for PR! Added some comments need to be addressed before merging.

2021-12-23 09:22 UTC, sept-en commented on tokens/pickle.svg
> +    <path d="M69.693 69.254c.143.974.02 1.296-.552 1.445-.613.161-.694.452-.487 1.747.209 1.31.138 1.554-.455 1.554-.568 0-.665.251-.505 1.3.243 1.591.019 2.3-.727 2.3-.648 0-.648.001-.194 2.349.3 1.
The icon is super-big, this won't work, unfortunately. Please try reducing it to 5-7 KB.

2021-12-23 09:22 UTC, sept-en commented on tokens/pickle.json
> +}
Please add "icon" field (even if it's empty if you can't convert it) and "aurora_address" - we deployed a contract for you on `0x291c8fceaca3342b29cc36171deb98106f712c66`

2021-12-24 11:15 UTC, larrythecucumber321 commented
Thank you for the feedback @sept-en! Hopefully this does the job 🙏

2021-12-24 11:36 UTC, sept-en approved these changes

2021-12-24 11:36 UTC, merged