Add CRF metadata
aurora-is-near/bridge-assets pull request #73
Opened 2022-01-03 05:56 UTC by CraftingFinance

2022-01-03 17:15 UTC, sept-en requested changes
Thanks for your PR. Please deploy the NEAR token first (check README) and update the PR description accordingly.

2022-01-04 05:01 UTC, CraftingFinance commented
We have deployed CRF token on Near.
CRF NEP-141 address: 508df5aa4746be37b5b6a69684dfd8bdc322219d.factory.bridge.near

2022-01-04 13:50 UTC, CraftingFinance commented
ERC-20: https://etherscan.io/address/0x508df5aa4746be37b5b6a69684dfd8bdc322219d
NEP-141: https://explorer.mainnet.near.org/accounts/508df5aa4746be37b5b6a69684dfd8bdc322219d.factory.bridge.near

2022-01-04 21:22 UTC, sept-en approved these changes

2022-01-04 21:22 UTC, merged