Add HAK token
aurora-is-near/bridge-assets pull request #75
Opened 2022-01-04 09:35 UTC by HTIMPL

2022-01-06 09:04 UTC, sept-en requested changes

2022-01-06 09:04 UTC, sept-en commented on tokens/HAK.svg
> +    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAABYmlDQ1BpY2MAAHjapdA9a1MBGMXx
The icon is too big. Please make sure it's 5-7 KB at max

2022-01-06 09:04 UTC, sept-en commented on tokens/HAK.json
> +"reference_hash": ""
This is not a valid JSON file. Also, please fix indents

2022-01-06 09:04 UTC, sept-en commented on assets/aurora.tokenlist.json
> +    },
Don't update that manually, this will be updated by Aurora team once PR is accepted and the metadata for the token is updated by us.

2022-01-06 09:04 UTC, sept-en commented
Also, please add an appropriate description for the PR (requirements are in README or use other PRs as example)

2022-01-13 08:55 UTC, nearhak commented
created a new pull https://github.com/aurora-is-near/bridge-assets/pull/81 @sept-en

2022-01-13 21:43 UTC, sept-en commented
Closed in favor of #81

2022-01-13 21:43 UTC, closed without merging